#!/bin/sh -e

. /lib/lsb/init-functions

_PROJECT_NAME="nubomedia-paas"
_PROJECT_BASE=/usr
_PROJECT_LOGS_FOLDER=/var/log/nubomedia

USER="$(id -un 2>/dev/null || true)"

checkBinary () {
    if command -v $1 >/dev/null 2>&1 ; then
        log_success_msg "Checking for '$1'" 
        return 0
    else
        log_failure_msg "Checking for '$1'"
        return 1
    fi
}

_ex='sh -c'
if [ "${USER}" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


#################
#### Project ####
#################

stopProject () {
    instance=$(ps aux | grep -v grep | grep "${_PROJECT_NAME}-*jar" | wc -l)
    if [ ${instance} -ne 0 ]; then
        if $_ex 'systemctl stop '"${_PROJECT_NAME}"'.service' >/dev/null ; then
    	    log_success_msg "Stopping the ${_PROJECT_NAME} ..."
        elif $_ex 'stop nubomedia-paas' >/dev/null ; then
    	    log_success_msg "Stopping the ${_PROJECT_NAME} ..."
        else
            log_failure_msg "Stopping the ${_PROJECT_NAME} ..."
        fi
    fi
}

stopProject

